#!/bin/bash
# Simple script to install git hooks
# Run this after cloning: ./hooks/install

cp hooks/pre-commit .git/hooks/pre-commit
cp hooks/commit-msg .git/hooks/commit-msg
chmod +x .git/hooks/pre-commit
chmod +x .git/hooks/commit-msg

echo "Git hooks installed!"
